/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIAutenticacion;

/**
 *
 * @author equipo aereostars
 */
public class GUIRegistro extends javax.swing.JFrame {

    /**
     * Creates new form GUIRegistro
     */
    public GUIRegistro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_regName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_regUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_regEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_regPwd = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_regExit = new javax.swing.JButton();
        btn_registerAdmin = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre completo");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 42, -1, -1));
        getContentPane().add(txt_regName, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 67, 206, -1));

        jLabel2.setText("Nombre de usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 105, -1, -1));
        getContentPane().add(txt_regUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 130, 206, -1));

        jLabel3.setText("Correo electronico");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 42, -1, -1));
        getContentPane().add(txt_regEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 67, 206, -1));

        jLabel4.setText("Contraseña");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 105, -1, -1));
        getContentPane().add(txt_regPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 130, 206, -1));

        btn_register.setText("Registrarse");
        getContentPane().add(btn_register, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 168, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mensaje");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        btn_regExit.setText("Salir");
        btn_regExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regExitActionPerformed(evt);
            }
        });
        getContentPane().add(btn_regExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(645, 354, -1, -1));

        btn_registerAdmin.setText("Registrarse como administrador");
        getContentPane().add(btn_registerAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 168, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/aereostars.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 200, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home_wallpaper_0.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_regExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_regExit;
    public javax.swing.JButton btn_register;
    public javax.swing.JButton btn_registerAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txt_regEmail;
    public javax.swing.JTextField txt_regName;
    public javax.swing.JTextField txt_regPwd;
    public javax.swing.JTextField txt_regUser;
    // End of variables declaration//GEN-END:variables
}
