/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIPaquetes;

/**
 *
 * @author equipo aereostars
 */
public class GUIAgregarPaquete extends javax.swing.JFrame {

    /**
     * Creates new form GUIAgregarPaquete
     */
    public GUIAgregarPaquete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chk_hotel = new javax.swing.JCheckBox();
        chk_evento = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_inputAddFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txt_inputAddHoraSalida = new javax.swing.JTextField();
        txt_inputAddOrigen = new javax.swing.JTextField();
        btn_agregarPaquete = new javax.swing.JButton();
        txt_inputAddDestino = new javax.swing.JTextField();
        btn_cancelarAgregarPaquete = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_inputReferencia = new javax.swing.JLabel();
        txt_inputAddTipo = new javax.swing.JTextField();
        txt_inputAddNumRef = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_inputAddCosto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        chk_hotel.setText("Hotel");
        chk_hotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_hotelActionPerformed(evt);
            }
        });
        getContentPane().add(chk_hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 217, -1, -1));

        chk_evento.setText("Evento");
        getContentPane().add(chk_evento, new org.netbeans.lib.awtextra.AbsoluteConstraints(92, 217, -1, -1));

        jLabel4.setText("Ingresa el costo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 156, -1, -1));

        jLabel5.setText("Ingresa la hora de salida:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 68, -1, -1));
        getContentPane().add(txt_inputAddFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 42, 156, -1));

        jLabel6.setText("Ingresa la fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 23, -1, -1));

        jLabel1.setText("Ingresa el origen:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 22, -1, -1));
        getContentPane().add(txt_inputAddHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 88, 156, -1));
        getContentPane().add(txt_inputAddOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 42, 156, -1));

        btn_agregarPaquete.setForeground(new java.awt.Color(0, 204, 51));
        btn_agregarPaquete.setText("Agregar");
        getContentPane().add(btn_agregarPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 176, -1, -1));
        getContentPane().add(txt_inputAddDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 88, 156, -1));

        btn_cancelarAgregarPaquete.setForeground(new java.awt.Color(204, 51, 0));
        btn_cancelarAgregarPaquete.setText("Cancelar");
        getContentPane().add(btn_cancelarAgregarPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(274, 176, -1, -1));

        jLabel2.setText("Ingresa el destino:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 68, -1, -1));

        txt_inputReferencia.setText("Ingresa núm. referencia:");
        getContentPane().add(txt_inputReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 108, -1, -1));
        getContentPane().add(txt_inputAddTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 128, 156, -1));
        getContentPane().add(txt_inputAddNumRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 128, 156, -1));

        jLabel3.setText("Ingresa el tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 108, -1, -1));
        getContentPane().add(txt_inputAddCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 179, 156, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home_wallpaper_0.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-450, 0, 840, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chk_hotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_hotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_hotelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAgregarPaquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarPaquete;
    public javax.swing.JButton btn_cancelarAgregarPaquete;
    private javax.swing.JCheckBox chk_evento;
    private javax.swing.JCheckBox chk_hotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    public javax.swing.JTextField txt_inputAddCosto;
    public javax.swing.JTextField txt_inputAddDestino;
    public javax.swing.JTextField txt_inputAddFecha;
    public javax.swing.JTextField txt_inputAddHoraSalida;
    public javax.swing.JTextField txt_inputAddNumRef;
    public javax.swing.JTextField txt_inputAddOrigen;
    public javax.swing.JTextField txt_inputAddTipo;
    private javax.swing.JLabel txt_inputReferencia;
    // End of variables declaration//GEN-END:variables
}
