/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIPaquetes;

/**
 *
 * @author equipo aereostars
 */
public class GUIModificarPaquete extends javax.swing.JFrame {

    /**
     * Creates new form GUIModificarPaquete
     */
    public GUIModificarPaquete() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_paqModSubmit = new javax.swing.JButton();
        btn_paqModExit = new javax.swing.JButton();
        txt_paqModValue = new javax.swing.JTextField();
        rad_paqCosto = new javax.swing.JRadioButton();
        rad_paqHora = new javax.swing.JRadioButton();
        rad_paqFecha = new javax.swing.JRadioButton();
        rad_paqTipo = new javax.swing.JRadioButton();
        rad_paqDestino = new javax.swing.JRadioButton();
        rad_paqOrigen = new javax.swing.JRadioButton();
        txt_paqModRef = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_paqModSubmit.setText("Realizar cambios");
        getContentPane().add(btn_paqModSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 250, -1, -1));

        btn_paqModExit.setText("Cancelar");
        getContentPane().add(btn_paqModExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 250, -1, -1));
        getContentPane().add(txt_paqModValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 156, 147, -1));

        rad_paqCosto.setText("Costo");
        getContentPane().add(rad_paqCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 209, -1, -1));

        rad_paqHora.setText("Hora de salida");
        getContentPane().add(rad_paqHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 183, -1, -1));

        rad_paqFecha.setText("Fecha de salida");
        getContentPane().add(rad_paqFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 155, -1, -1));

        rad_paqTipo.setText("Tipo");
        getContentPane().add(rad_paqTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 131, -1, -1));

        rad_paqDestino.setText("Destino");
        getContentPane().add(rad_paqDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 107, -1, -1));

        rad_paqOrigen.setText("Origen");
        getContentPane().add(rad_paqOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 84, -1, -1));
        getContentPane().add(txt_paqModRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 46, 138, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ID PAQUETE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 26, -1, -1));

        jLabel8.setText("Nuevo valor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 135, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home_wallpaper_0.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIModificarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIModificarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIModificarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIModificarPaquete.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIModificarPaquete().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_paqModExit;
    public javax.swing.JButton btn_paqModSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JRadioButton rad_paqCosto;
    public javax.swing.JRadioButton rad_paqDestino;
    public javax.swing.JRadioButton rad_paqFecha;
    public javax.swing.JRadioButton rad_paqHora;
    public javax.swing.JRadioButton rad_paqOrigen;
    public javax.swing.JRadioButton rad_paqTipo;
    public javax.swing.JTextField txt_paqModRef;
    public javax.swing.JTextField txt_paqModValue;
    // End of variables declaration//GEN-END:variables
}
