/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIHoteles;

/**
 *
 * @author jovan
 */
public class GUIAgregarHotel extends javax.swing.JFrame {

    /**
     * Creates new form GUIHoteles
     */
    public GUIAgregarHotel() {
        initComponents();
        this.setTitle("AGREGAR HOTEL");
        this.setLocation(400,220);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        label5 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        btn_agregar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        txt_hotel = new javax.swing.JLabel();
        txtnombre = new javax.swing.JTextField();
        txtnumref = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtnumestre = new javax.swing.JTextField();
        txtcosto = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label2.setText("ID");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 53, -1, -1));

        label3.setText("Direccion");
        getContentPane().add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 96, -1, -1));

        label4.setText("numero de estrellas ");
        getContentPane().add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 148, -1, -1));

        label5.setText("costo");
        getContentPane().add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 193, -1, -1));

        label1.setText("Nombre");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 15, -1, -1));

        btn_agregar.setText("AGREGAR");
        getContentPane().add(btn_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        btn_cancelar.setText("CANCELAR");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        txt_hotel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_hotel.setText("Agregar un hotel");
        getContentPane().add(txt_hotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));
        getContentPane().add(txtnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 150, -1));
        getContentPane().add(txtnumref, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, -1));
        getContentPane().add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 93, 105, -1));
        getContentPane().add(txtnumestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 40, -1));
        getContentPane().add(txtcosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 190, 60, -1));
        getContentPane().add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 119, 390, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/images/home_wallpaper_0.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
       GUIAgregarHotel.this.dispose();
    }//GEN-LAST:event_btn_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarHotel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAgregarHotel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel label1;
    public javax.swing.JLabel label2;
    public javax.swing.JLabel label3;
    public javax.swing.JLabel label4;
    public javax.swing.JLabel label5;
    private javax.swing.JLabel txt_hotel;
    public javax.swing.JTextField txt_id;
    public javax.swing.JTextField txtcosto;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtnombre;
    public javax.swing.JTextField txtnumestre;
    public javax.swing.JTextField txtnumref;
    // End of variables declaration//GEN-END:variables
}
