/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIHoteles;

import Controller.OyenteHoteles;
import Model.GestorHoteles.*;

/**
 *
 * @author jovan
 */
public class GUIHOTEL extends javax.swing.JFrame {

    /**
     * Creates new form GUIHOTEL
     */
           public Hotel h;
    public Relacion_hoteles modC;
    public GUIAgregarHotel frm;
    public GUIHOTEL() {
        initComponents();
        
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_agregarhotel = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modifica = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("gestor de hoteles");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 33, -1, -1));

        btn_agregarhotel.setText("AGREGAR UN HOTEL");
        btn_agregarhotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarhotelActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregarhotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btn_ver.setText("VER LOS HOTELES");
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ver, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 170, -1, -1));

        btn_eliminar.setText("ELIMINAR UN HOTEL");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 170, -1, -1));

        btn_modifica.setText("MODIFICAR HOTEL");
        btn_modifica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificaActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modifica, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, -1, -1));

        jLabel2.setText("SELECCIONE LA OPCION DESEADA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 96, -1, -1));

        getAccessibleContext().setAccessibleParent(btn_agregarhotel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_agregarhotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarhotelActionPerformed
        OyenteHoteles o = new OyenteHoteles();
        o.iniciar();
        //o.actionPerformed(evt);
      
        //GUIAgregarHotel g = new GUIAgregarHotel();
       //g.setVisible(true);
       
      // g.setVisible(false);
       //dispose();
    }//GEN-LAST:event_btn_agregarhotelActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_verActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_modificaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_modificaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHOTEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHOTEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHOTEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHOTEL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHOTEL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarhotel;
    public javax.swing.JButton btn_eliminar;
    public javax.swing.JButton btn_modifica;
    public javax.swing.JButton btn_ver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
