/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIVuelos;

import Controller.OVuelos;
import java.awt.event.ActionEvent;

/**
 *
 * @author equipo aereostars
 */
public class GUIAgregarVuelo extends javax.swing.JFrame {
    

    /**
     * Creates new form GUIAgregarVuelo
     */
    public GUIAgregarVuelo() {
        initComponents(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_inputAddOrigen = new javax.swing.JTextField();
        txt_inputAddDestino = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_inputAddTipo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_inputAddCosto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_inputAddFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_inputAddHoraSalida = new javax.swing.JTextField();
        btn_agregarVuelo = new javax.swing.JButton();
        btn_cancelarAgregarVuelo = new javax.swing.JButton();
        txt_inputReferencia = new javax.swing.JLabel();
        txt_inputAddNumRef = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Ingresa el origen:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, -1, -1));
        getContentPane().add(txt_inputAddOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 43, 156, -1));
        getContentPane().add(txt_inputAddDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 89, 156, -1));

        jLabel2.setText("Ingresa el destino:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 69, -1, -1));
        getContentPane().add(txt_inputAddTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 129, 156, -1));

        jLabel3.setText("Ingresa el tipo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 109, -1, -1));
        getContentPane().add(txt_inputAddCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 180, 156, -1));

        jLabel4.setText("Ingresa el costo:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 157, -1, -1));

        jLabel5.setText("Ingresa la hora de salida:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 69, -1, -1));
        getContentPane().add(txt_inputAddFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 43, 156, -1));

        jLabel6.setText("Ingresa la fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 24, -1, -1));
        getContentPane().add(txt_inputAddHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 89, 156, -1));

        btn_agregarVuelo.setForeground(new java.awt.Color(0, 204, 51));
        btn_agregarVuelo.setText("Agregar");
        getContentPane().add(btn_agregarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 177, -1, -1));

        btn_cancelarAgregarVuelo.setForeground(new java.awt.Color(204, 51, 0));
        btn_cancelarAgregarVuelo.setText("Cancelar");
        getContentPane().add(btn_cancelarAgregarVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(285, 177, -1, -1));

        txt_inputReferencia.setText("Ingresa núm. referencia:");
        getContentPane().add(txt_inputReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 109, -1, -1));
        getContentPane().add(txt_inputAddNumRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 129, 156, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home_wallpaper_0.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAgregarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
            
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAgregarVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_agregarVuelo;
    public javax.swing.JButton btn_cancelarAgregarVuelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JTextField txt_inputAddCosto;
    public javax.swing.JTextField txt_inputAddDestino;
    public javax.swing.JTextField txt_inputAddFecha;
    public javax.swing.JTextField txt_inputAddHoraSalida;
    public javax.swing.JTextField txt_inputAddNumRef;
    public javax.swing.JTextField txt_inputAddOrigen;
    public javax.swing.JTextField txt_inputAddTipo;
    private javax.swing.JLabel txt_inputReferencia;
    // End of variables declaration//GEN-END:variables
}
