/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIVuelos;

import javax.swing.ButtonGroup;

/**
 *
 * @author equipo aereostars
 */
public class GUIModificarVuelo extends javax.swing.JFrame {

    public ButtonGroup grp;
    /**
     * Creates new form GUIModificarVuelo
     */
    public GUIModificarVuelo() {
        initComponents();
        grp = new ButtonGroup();
        grp.add(rad_vueloCosto);
        grp.add(rad_vueloDestino);
        grp.add(rad_vueloFecha);
        grp.add(rad_vueloHora);
        grp.add(rad_vueloOrigen);
        grp.add(rad_vueloTipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_vueloModValue = new javax.swing.JTextField();
        btn_vueloModSubmit = new javax.swing.JButton();
        btn_vueloModClose = new javax.swing.JButton();
        rad_vueloOrigen = new javax.swing.JRadioButton();
        txt_vueloModRef = new javax.swing.JTextField();
        rad_vueloDestino = new javax.swing.JRadioButton();
        rad_vueloTipo = new javax.swing.JRadioButton();
        rad_vueloFecha = new javax.swing.JRadioButton();
        rad_vueloHora = new javax.swing.JRadioButton();
        rad_vueloCosto = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NUMERO DE REFERENCIA DE VUELO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 30, -1, -1));

        jLabel8.setText("Nuevo valor");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 135, -1, -1));
        getContentPane().add(txt_vueloModValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(169, 155, 147, -1));

        btn_vueloModSubmit.setText("Realizar cambios");
        getContentPane().add(btn_vueloModSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 250, -1, -1));

        btn_vueloModClose.setText("Cancelar");
        getContentPane().add(btn_vueloModClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(269, 250, -1, -1));

        rad_vueloOrigen.setText("Origen");
        getContentPane().add(rad_vueloOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 88, -1, -1));
        getContentPane().add(txt_vueloModRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 50, 138, -1));

        rad_vueloDestino.setText("Destino");
        getContentPane().add(rad_vueloDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 111, -1, -1));

        rad_vueloTipo.setText("Tipo");
        getContentPane().add(rad_vueloTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 135, -1, -1));

        rad_vueloFecha.setText("Fecha de salida");
        getContentPane().add(rad_vueloFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 158, -1, -1));

        rad_vueloHora.setText("Hora de salida");
        getContentPane().add(rad_vueloHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 184, -1, -1));

        rad_vueloCosto.setText("Costo");
        getContentPane().add(rad_vueloCosto, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 210, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home_wallpaper_0.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIModificarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIModificarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIModificarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIModificarVuelo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIModificarVuelo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_vueloModClose;
    public javax.swing.JButton btn_vueloModSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JRadioButton rad_vueloCosto;
    public javax.swing.JRadioButton rad_vueloDestino;
    public javax.swing.JRadioButton rad_vueloFecha;
    public javax.swing.JRadioButton rad_vueloHora;
    public javax.swing.JRadioButton rad_vueloOrigen;
    public javax.swing.JRadioButton rad_vueloTipo;
    public javax.swing.JTextField txt_vueloModRef;
    public javax.swing.JTextField txt_vueloModValue;
    // End of variables declaration//GEN-END:variables
}
