/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUIPrincipal;

import Controller.OPrincipal;

/**
 *
 * @author equipo aereostars
 */
public class GUIPrincipalSocio extends javax.swing.JFrame {

    /**
     * Creates new form GUIPrincipal
     */
    OPrincipal op;
    public GUIPrincipalSocio() {
        initComponents();
        list_so.addItem("Vuelos");
        list_so.addItem("Paquetes");
        list_so.addItem("Hoteles");
        list_so.addItem("Promociones");
        list_so.addItem("Eventos");
        
        list2_so.addItem("Vuelo");
        list2_so.addItem("Paquete");
        list2_so.addItem("Hotel");
        list_so.setEditable(false);
        jTextField1.setEditable(false);
        list_so.setEditable(false);
        jTextField2.setEditable(false);
        
        /*op = new OPrincipal(jTextField1, jTextField2, list_so, list2_so, busca_so, reserva_so, paga_so, jButton4, che_so);
        busca_so.addActionListener(op);
        reserva_so.addActionListener(op);
        paga_so.addActionListener(op);
        jButton4.addActionListener(op);
        che_so.addActionListener(op);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        list_so = new javax.swing.JComboBox<>();
        list2_so = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        busca_so = new javax.swing.JButton();
        reserva_so = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        paga_so = new javax.swing.JButton();
        can_so = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        che_so = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Busqueda:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Bienvenido Socio!!!");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 0, -1, -1));

        jLabel3.setText("Reserva:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel4.setText("Pago de reservacion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jPanel1.add(list_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 140, -1));

        jPanel1.add(list2_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 140, -1));

        jLabel7.setText("Cancelar Reservacion:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 370, -1, -1));

        busca_so.setText("Ir a busqueda");
        jPanel1.add(busca_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        reserva_so.setText("Ir a reservacion");
        jPanel1.add(reserva_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 266, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 296, -1));

        paga_so.setText("Pagar");
        jPanel1.add(paga_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        can_so.setText("Cancelar");
        jPanel1.add(can_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 402, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/aereostars.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 98, 233, -1));

        jLabel6.setText("Realizar Check-in");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 370, -1, -1));

        che_so.setText("Check-in");
        jPanel1.add(che_so, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 402, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Images/home_wallpaper_0.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 1660, 610));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 0, 630, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipalSocio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipalSocio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton busca_so;
    public javax.swing.JButton can_so;
    public javax.swing.JButton che_so;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JComboBox<String> list2_so;
    public javax.swing.JComboBox<String> list_so;
    public javax.swing.JButton paga_so;
    public javax.swing.JButton reserva_so;
    // End of variables declaration//GEN-END:variables
}
